sonar.projectKey=ricartefelipe_reactmind2
sonar.organization=ricartefelipe

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/mocks/**,**/public/**,**/shared/mind-wallet/**,**/archive/malha/**

sonar.cpd.exclusions=**/shared/mind-wallet/**,**/archive/malha/**,**/i18n/locales/**

sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts

sonar.typescript.tsconfigPath=tsconfig.app.json
